# Generated by Django 4.2.7 on 2025-10-31 18:14

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EuropeanCity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("population", models.IntegerField()),
                ("country", models.CharField(max_length=100)),
                ("geom", django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                "verbose_name": "European City",
                "verbose_name_plural": "European Cities",
                "db_table": "european_cities",
                "ordering": ["-population"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="IrishCounty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("osm_id", models.FloatField(blank=True, null=True)),
                ("name_tag", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "name_ga",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Irish Name"
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="English Name",
                    ),
                ),
                (
                    "alt_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Alternative Name",
                    ),
                ),
                (
                    "area",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=31, null=True
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=31, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=31, null=True
                    ),
                ),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
                ),
            ],
            options={
                "verbose_name": "Irish County",
                "verbose_name_plural": "Irish Counties",
                "db_table": "irish_counties",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TransportationRoute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("route_name", models.CharField(max_length=100)),
                (
                    "route_type",
                    models.CharField(
                        choices=[
                            ("highway", "Highway"),
                            ("railway", "Railway"),
                            ("waterway", "Waterway"),
                            ("airway", "Airway"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.LineStringField(srid=4326),
                ),
            ],
            options={
                "verbose_name": "Transportation Route",
                "verbose_name_plural": "Transportation Routes",
                "db_table": "transportation_routes",
                "managed": False,
            },
        ),
    ]
