# Generated by Django 4.2.7 on 2025-11-02 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cities", "0002_add_spatial_indexes"),
    ]

    operations = []
