# Generated by Django 4.2.7 on 2025-11-02 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cities", "0003_auto_20251102_1744"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="city",
            index=models.Index(fields=["name"], name="cities_city_name_a4d1d7_idx"),
        ),
        migrations.AddIndex(
            model_name="city",
            index=models.Index(
                fields=["country"], name="cities_city_country_6d703a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="city",
            index=models.Index(
                fields=["latitude", "longitude"], name="cities_city_latitud_3b65e7_idx"
            ),
        ),
    ]
