# Generated by Django 4.2.7 on 2025-11-04 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cities_query", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(name="City",),
    ]
